language: ruby
rvm:
  - "1.9.2"
  - "1.9.3"
  - rbx-19mode
  - ruby-head
branches:
  only:
    - master
# uncomment this line if your project needs to run something other than `rake`:
# # script: bundle exec rspec spec
